import{S as f,i as n}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))e(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&e(i)}).observe(document,{childList:!0,subtree:!0});function a(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function e(r){if(r.ep)return;r.ep=!0;const t=a(r);fetch(r.href,t)}})();function d(s){return fetch(`https://pixabay.com/api?key=45098257-09112d803d024f473cdacef7f&q=${s}&image_type=photo&orientation=horizontal&safesearch=true`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}const c=document.querySelector(".gallery");function u(s){const o=s.hits.map(e=>`<li class="gallery-item">
        <a class="gallery-link" href="${e.largeImageURL}">
        <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}"/>
        </a>
        <div class="gallery-wrapper">
        <div class="text-wrap"><h3>Likes</h3><p>${e.likes}</p></div>
        <div class="text-wrap"><h3>Views</h3><p>${e.views}</p></div>
        <div class="text-wrap"><h3>Comments</h3><p>${e.comments}</p></div>
        <div class="text-wrap"><h3>Downloads</h3><p>${e.downloads}</p></div>
        </div>
        </li>`).join("");c.insertAdjacentHTML("afterbegin",o),new f(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function m(){c.innerHTML=""}const p=document.querySelector(".search-form"),l=document.querySelector(".loader");p.addEventListener("submit",g);function g(s){s.preventDefault(),m(),l.classList.add("loader-active");const o=s.currentTarget,a=o.elements.search.value.trim();d(a).then(e=>{if(e.total===0||a==="")return n.error({title:"Error",titleColor:"#fff",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff",theme:"dark"});u(e),l.classList.remove("loader-active")}).catch(e=>n.error({title:"Error",titleColor:"#fff",message:`${e}`,position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff",theme:"dark"})).finally(()=>{o.reset(),l.classList.remove("loader-active")})}
//# sourceMappingURL=commonHelpers.js.map
