import{a as p,i,S as h}from"./assets/vendor-ee72e1a4.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const y="https://pixabay.com/api/",v="45098257-09112d803d024f473cdacef7f";async function L(t,a=1){try{return(await p.get(y,{params:{key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:15}})).data}catch(s){return i.error({title:"Error",titleColor:"#fff",message:`${s}`,position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff",theme:"dark"})}}const m=document.querySelector(".gallery");function w(t){const a=t.hits.map(o=>`<li class="gallery-item">
        <a class="gallery-link" href="${o.largeImageURL}">
        <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}"/>
        </a>
        <div class="gallery-wrapper">
        <div class="text-wrap"><h3>Likes</h3><p>${o.likes}</p></div>
        <div class="text-wrap"><h3>Views</h3><p>${o.views}</p></div>
        <div class="text-wrap"><h3>Comments</h3><p>${o.comments}</p></div>
        <div class="text-wrap"><h3>Downloads</h3><p>${o.downloads}</p></div>
        </div>
        </li>`).join("");m.insertAdjacentHTML("beforeend",a),new h(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function b(){m.innerHTML=""}const d=document.querySelector(".search-form"),u=document.querySelector(".loader"),l=document.querySelector(".load-btn");let n=1,f="";d.addEventListener("submit",C);l.addEventListener("click",S);async function C(t){t.preventDefault(),b(),u.classList.add("loader-active"),f=d.elements.search.value.trim(),n=1,await g(),d.reset()}async function g(){try{const t=await L(f,n);if(u.classList.remove("loader-active"),w(t),x(),t.total===0||f==="")return l.classList.add("hidden"),i.error({title:"Error",titleColor:"#fff",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff",theme:"dark"});if(t.hits.length===0||n*15>=t.totalHits)return l.classList.add("hidden"),i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."});l.classList.remove("hidden")}catch(t){return i.error({title:"Error",titleColor:"#fff",message:`${t}`,position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff",theme:"dark"})}}async function S(){n+=1,u.classList.add("loader-active"),await g()}function x(){const a=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
